/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movil;

import java.awt.Color;
import clases.Parqueadero;
import ventanas.InterfazPrincipal;

/**
 *
 * @author angel
 */
public class InterfazMovil extends javax.swing.JFrame {

    protected InterfazMovilMapa interfazMovilMapa;
    protected InterfazMovilInfo interfazMovilInfo;
    protected InterfazPrincipal interfaz; 
    /**
     * Creates new form Interfaz
     */
    public InterfazMovil(InterfazPrincipal interfaz) {
        
        this.interfaz=interfaz;
        
        initComponents();
        
        this.interfazMovilMapa=new InterfazMovilMapa(this);
        this.interfazMovilInfo=new InterfazMovilInfo(this);
        
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jLabelEstadoGeneral = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabelConsultarRuta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelConsultarRuta1 = new javax.swing.JLabel();
        jComboBoxRutas = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 255, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_movil/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 300, 150));

        jButtonSalir.setBackground(new java.awt.Color(51, 153, 0));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 70, -1));

        jLabelEstadoGeneral.setBackground(new java.awt.Color(0, 0, 0));
        jLabelEstadoGeneral.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabelEstadoGeneral.setText("Estado Parqueadero");
        getContentPane().add(jLabelEstadoGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jButton5.setBackground((this.interfaz.getParqueadero().getEstadoGeneral()=="No disponible")? Color.red : Color.green /*A esto se le llama operador ternario, es un if en una sola línea para java*/);
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton5.setText(this.interfaz.getParqueadero().getEstadoGeneral());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 250, 60));

        jLabelConsultarRuta.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelConsultarRuta.setText("Mensaje General:");
        getContentPane().add(jLabelConsultarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jTextArea1.setColumns(1);
        jTextArea1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(1);
        jTextArea1.setText("Sin mensajes...");
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 370, 80));

        jLabelConsultarRuta1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelConsultarRuta1.setText("Consultar Ruta:");
        getContentPane().add(jLabelConsultarRuta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jComboBoxRutas.setBackground(new java.awt.Color(51, 153, 0));
        jComboBoxRutas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Luis A. Calvo (1-15)", "Administración (16-30)", "Bienestar Universitario (31-45)", "Jardín de las Orquídeas (46-60)", "Escuela de Música (61-75)", "Laboratorios Livianos (76-90)" }));
        jComboBoxRutas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxRutasItemStateChanged(evt);
            }
        });
        jComboBoxRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRutasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxRutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 270, 30));

        jButtonBuscar.setBackground(new java.awt.Color(51, 153, 0));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 80, 30));

        jButton1.setBackground(new java.awt.Color(51, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("¿Cómo usar el parqueadero?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, 270, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_movil/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBoxRutasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxRutasItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRutasItemStateChanged

    private void jComboBoxRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRutasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRutasActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        this.interfazMovilMapa.setVisible(true);
        this.interfazMovilMapa.setJComboBox(this.jComboBoxRutas);
        this.interfazMovilMapa.actualizarVentana();
        this.setVisible(false);

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.interfazMovilInfo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void actualizarVentana(){
        this.jButton5.setBackground((interfaz.getParqueadero().getEstadoGeneral()=="No disponible")? Color.red : Color.green);
        this.jButton5.setText(interfaz.getParqueadero().getEstadoGeneral());
        this.jTextArea1.setText(this.interfaz.getParqueadero().getMensajeGeneral());
    }
    
    public javax.swing.JTextArea getJTextArea(){
        return this.jTextArea1;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxRutas;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelConsultarRuta;
    private javax.swing.JLabel jLabelConsultarRuta1;
    private javax.swing.JLabel jLabelEstadoGeneral;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
