/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movil;

import java.awt.Color;
import clases.Parqueadero;
import ventanas.InterfazPrincipal;

/**
 *
 * @author angel
 */
public class InterfazMovilInfo extends javax.swing.JFrame {

    protected InterfazMovil interfazMovil; 
    /**
     * Creates new form Interfaz
     */
    public InterfazMovilInfo(InterfazMovil interfazMovil) {
        
        this.interfazMovil=interfazMovil;
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConsultarRuta1 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jLabelConsultarRuta2 = new javax.swing.JLabel();
        jLabelConsultarRuta3 = new javax.swing.JLabel();
        jLabelConsultarRuta4 = new javax.swing.JLabel();
        jLabelConsultarRuta5 = new javax.swing.JLabel();
        jLabelConsultarRuta6 = new javax.swing.JLabel();
        jLabelConsultarRuta7 = new javax.swing.JLabel();
        jLabelConsultarRuta8 = new javax.swing.JLabel();
        jLabelConsultarRuta9 = new javax.swing.JLabel();
        jLabelConsultarRuta10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelConsultarRuta11 = new javax.swing.JLabel();
        jLabelConsultarRuta12 = new javax.swing.JLabel();
        jLabelConsultarRuta13 = new javax.swing.JLabel();
        jLabelConsultarRuta14 = new javax.swing.JLabel();
        jLabelConsultarRuta15 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelConsultarRuta1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelConsultarRuta1.setText("1 Semestre de ingreso de vehiculo : $ 180000 COP");
        getContentPane().add(jLabelConsultarRuta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(51, 153, 0));
        jButtonSalir.setText("Volver");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 70, -1));

        jLabelConsultarRuta2.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabelConsultarRuta2.setText("¿Cómo usar el parqueadero?");
        getContentPane().add(jLabelConsultarRuta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabelConsultarRuta3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelConsultarRuta3.setText("El parqueadero cobra por ingreso, no por hora. Además,");
        getContentPane().add(jLabelConsultarRuta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabelConsultarRuta4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelConsultarRuta4.setText("los precios varían de acuerdo a si se paga por ingreso, ");
        getContentPane().add(jLabelConsultarRuta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabelConsultarRuta5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelConsultarRuta5.setText("cualquiera de nuestras cafeterias.");
        getContentPane().add(jLabelConsultarRuta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabelConsultarRuta6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelConsultarRuta6.setText("Domingo: 8 am a 1 pm");
        getContentPane().add(jLabelConsultarRuta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, -1, -1));

        jLabelConsultarRuta7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelConsultarRuta7.setText("1 Ingeso de vehiculo : $ 1500 COP");
        getContentPane().add(jLabelConsultarRuta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabelConsultarRuta8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelConsultarRuta8.setText("1 Mes de ingreso de vehiculo : $ 33000 COP");
        getContentPane().add(jLabelConsultarRuta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabelConsultarRuta9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelConsultarRuta9.setText("por el mes completo o por el semestre completo.");
        getContentPane().add(jLabelConsultarRuta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabelConsultarRuta10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelConsultarRuta10.setText("El costo de ingreso podrá ser cancelado en las taquillas");
        getContentPane().add(jLabelConsultarRuta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 450, 10));

        jLabelConsultarRuta11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelConsultarRuta11.setText("Precios:");
        getContentPane().add(jLabelConsultarRuta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabelConsultarRuta12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelConsultarRuta12.setText("Horarios de atención:");
        getContentPane().add(jLabelConsultarRuta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabelConsultarRuta13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelConsultarRuta13.setText("Lunes a Viernes: 6 am a 10 pm");
        getContentPane().add(jLabelConsultarRuta13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jLabelConsultarRuta14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelConsultarRuta14.setText("Sabado: 8 am a 6 pm");
        getContentPane().add(jLabelConsultarRuta14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        jLabelConsultarRuta15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelConsultarRuta15.setText("del auditorio Luis A. Calvo, en la tienda UIS y en");
        getContentPane().add(jLabelConsultarRuta15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_movil/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.interfazMovil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelConsultarRuta1;
    private javax.swing.JLabel jLabelConsultarRuta10;
    private javax.swing.JLabel jLabelConsultarRuta11;
    private javax.swing.JLabel jLabelConsultarRuta12;
    private javax.swing.JLabel jLabelConsultarRuta13;
    private javax.swing.JLabel jLabelConsultarRuta14;
    private javax.swing.JLabel jLabelConsultarRuta15;
    private javax.swing.JLabel jLabelConsultarRuta2;
    private javax.swing.JLabel jLabelConsultarRuta3;
    private javax.swing.JLabel jLabelConsultarRuta4;
    private javax.swing.JLabel jLabelConsultarRuta5;
    private javax.swing.JLabel jLabelConsultarRuta6;
    private javax.swing.JLabel jLabelConsultarRuta7;
    private javax.swing.JLabel jLabelConsultarRuta8;
    private javax.swing.JLabel jLabelConsultarRuta9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
