package ventanas;
import clases.Parqueadero;
import clases.Admin;
import clases.Fabrica;
import movil.*;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.SwingUtilities;

/**
 *
 * @author Juan Ricardo y Angel
 */

public class InterfazPrincipal extends javax.swing.JFrame {
    //public int contador;
    //Objetos
    private Parqueadero parq;
    private Fabrica fabrica;
    private Admin admin;
    //Ventanas
    private VentanaLogin ventanaLogin;
    private AvisoCerrarSesion avisoCerrarSesion;
    private AvisoEstadoGeneral avisoEstadoGeneral;
    private VentanaComuneros ventanaComuneros;
    private VentanaSanFrancisco ventanaSanFrancisco;
    private VentanaDiamanteII ventanaDiamanteII;
    private VentanaPiedecuesta ventanaPiedecuesta;
    private VentanaCabecera ventanaCabecera;
    private VentanaRealDeMinas ventanaRealDeMinas;
    private InterfazMovil interfazMovil;
    private VentanaMensajeGeneral ventanaMensajeGeneral;
    private VentanaRegistros ventanaRegistros;
    
    /**
     * Creates new form Interface
     */
    public InterfazPrincipal(Admin admin, VentanaLogin ventanaLogin) {
        
        this.admin = admin;
        this.parq = new Parqueadero();
        this.fabrica = new Fabrica(parq);
        
        //this.contador=parq.getPlazasOcupadas().size();
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.ventanaLogin = ventanaLogin;
        
        this.avisoCerrarSesion = new AvisoCerrarSesion(this);
        this.avisoCerrarSesion.setLocationRelativeTo(null);
        
        this.avisoEstadoGeneral = new AvisoEstadoGeneral(parq,this);
        this.avisoEstadoGeneral.setLocationRelativeTo(null);
        
        this.ventanaComuneros = new VentanaComuneros(parq,this);
        this.ventanaComuneros.setLocationRelativeTo(null);
        
        this.ventanaSanFrancisco = new VentanaSanFrancisco(parq,this);
        this.ventanaSanFrancisco.setLocationRelativeTo(null);
        
        this.ventanaDiamanteII = new VentanaDiamanteII(parq,this);
        this.ventanaDiamanteII.setLocationRelativeTo(null);
        
        this.ventanaPiedecuesta = new VentanaPiedecuesta(parq,this);
        this.ventanaPiedecuesta.setLocationRelativeTo(null);
        
        this.ventanaCabecera = new VentanaCabecera(parq,this);
        this.ventanaCabecera.setLocationRelativeTo(null);
        
        this.ventanaRealDeMinas = new VentanaRealDeMinas(parq,this);
        this.ventanaRealDeMinas.setLocationRelativeTo(null);
        
        this.ventanaMensajeGeneral=new VentanaMensajeGeneral(this);
        this.ventanaMensajeGeneral.setLocationRelativeTo(null);
        
        this.ventanaRegistros = new VentanaRegistros(parq, this);
        this.ventanaRegistros.setLocationRelativeTo(null);
        
        this.interfazMovil = new InterfazMovil(this);
        this.interfazMovil.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton8 = new javax.swing.JButton();
        plazasDisponibles = new javax.swing.JLabel();
        plazasOcupadas = new javax.swing.JLabel();
        plazasTotal1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        labelInfoGeneral = new javax.swing.JLabel();
        labelBienvenido = new javax.swing.JLabel();
        labelNombreUsuario = new javax.swing.JLabel();
        cerrarSesion = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("SISTEMA DE PARQUEO DE AUTOMÓVILES");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PIEDECUESTA (46-60)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 330, 70));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REAL DE MINAS (76-90)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 330, 70));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("COMUNEROS (1-15)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 330, 70));

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CABECERA (61-75)");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 330, 70));

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("DIAMANTE II (31-45)");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 330, 70));

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("SAN FRANCISCO(16-30)");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 330, 70));

        jLabel2.setFont(new java.awt.Font("Corbel Light", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mensaje de disponibilidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 260, 20));

        jButton5.setBackground((parq.getEstadoGeneral()=="No disponible")? Color.red : Color.green /*A esto se le llama operador ternario, es un if en una sola línea para java*/);
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton5.setText(parq.getEstadoGeneral());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 250, 60));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONSULTAR PARQUEADERO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 370, 20));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Plazas ocupadas: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total de plazas: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Plazas disponibles: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jButton9.setBackground(new java.awt.Color(51, 51, 255));
        jButton9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/preferences_desktop_notification_opt.png"))); // NOI18N
        jButton9.setText("Mensaje General");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 130, 160, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 204, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 204, 51));
        jSeparator1.setFocusable(true);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 82, 960, 20));

        jButton8.setText("CAMBIAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        plazasDisponibles.setBackground(new java.awt.Color(255, 255, 255));
        plazasDisponibles.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        plazasDisponibles.setForeground(new java.awt.Color(255, 255, 255));
        plazasDisponibles.setText(Integer.toString(parq.getPlazasOcupadas().size()));
        getContentPane().add(plazasDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        plazasOcupadas.setBackground(new java.awt.Color(255, 255, 255));
        plazasOcupadas.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        plazasOcupadas.setForeground(new java.awt.Color(255, 255, 255));
        plazasOcupadas.setText(Integer.toString(parq.getPlazasLibres().size()));
        getContentPane().add(plazasOcupadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        plazasTotal1.setBackground(new java.awt.Color(255, 255, 255));
        plazasTotal1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        plazasTotal1.setForeground(new java.awt.Color(255, 255, 255));
        plazasTotal1.setText(Integer.toString(parq.getPlazas().size()));
        getContentPane().add(plazasTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        jButton10.setBackground(new java.awt.Color(51, 51, 255));
        jButton10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gtk_find_and_replace_opt.png"))); // NOI18N
        jButton10.setText("Ver Registros");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 160, 30));

        labelInfoGeneral.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        labelInfoGeneral.setForeground(new java.awt.Color(255, 255, 255));
        labelInfoGeneral.setText("INFORMACIÓN GENERAL:");
        getContentPane().add(labelInfoGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, 20));

        labelBienvenido.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        labelBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        labelBienvenido.setText("Bienvenido");
        getContentPane().add(labelBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, 20));

        labelNombreUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        labelNombreUsuario.setForeground(new java.awt.Color(51, 255, 51));
        labelNombreUsuario.setText(this.admin.getPrimerNombre()+" "+this.admin.getPrimerApellido());
        getContentPane().add(labelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 290, 30));

        cerrarSesion.setBackground(new java.awt.Color(153, 0, 0));
        cerrarSesion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 140, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pavement-yellow-lines-parking_1.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1200, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       ventanaPiedecuesta.actualizarVentana();
       ventanaPiedecuesta.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ventanaRealDeMinas.actualizarVentana();
        ventanaRealDeMinas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       ventanaComuneros.actualizarVentana();
       ventanaComuneros.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       ventanaCabecera.actualizarVentana();
       ventanaCabecera.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       ventanaDiamanteII.actualizarVentana();
       ventanaDiamanteII.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       // TODO add your handling code here:
       ventanaSanFrancisco.actualizarVentana();
       ventanaSanFrancisco.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        ventanaMensajeGeneral.actualizarVentana();
        ventanaMensajeGeneral.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        avisoEstadoGeneral.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
       ventanaRegistros.setVisible(true);
       this.setVisible(false);
       ventanaRegistros.mostrarTabla();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        // TODO add your handling code here:
        this.avisoCerrarSesion.setVisible(true);
    }//GEN-LAST:event_cerrarSesionActionPerformed

    public Parqueadero getParqueadero(){
        return this.parq;
    }
    
    public InterfazMovil getInterfazMovil(){
        return this.interfazMovil;
    }
    
    public Admin getAdmin(){
        return this.admin;
    }
    
    public VentanaLogin getVentanaLogin(){
        return this.ventanaLogin;
    }
    /**
     * Cree este método para poder cambiar la ventana de disponibilidad desde el avisoEstadoGeneral de alerta de cambio.
     */
    public void actualizarInterfaz(){
        this.jButton5.setBackground((parq.getEstadoGeneral()=="No disponible")? Color.red : Color.green);//A esto se le llama operador ternario, es un if en una sola línea para java
        this.jButton5.setText(parq.getEstadoGeneral());
        this.plazasTotal1.setText(Integer.toString(parq.getPlazas().size()));
        this.plazasOcupadas.setText(Integer.toString(parq.getPlazasLibres().size()));
        this.plazasDisponibles.setText(Integer.toString(parq.getPlazasOcupadas().size()));
        this.labelNombreUsuario.setText(this.admin.getPrimerNombre()+" "+this.admin.getPrimerApellido());
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBienvenido;
    private javax.swing.JLabel labelInfoGeneral;
    private javax.swing.JLabel labelNombreUsuario;
    private javax.swing.JLabel plazasDisponibles;
    private javax.swing.JLabel plazasOcupadas;
    private javax.swing.JLabel plazasTotal1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
