/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.awt.Desktop;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import clases.Plaza;
import clases.Ticket;

/**
 *
 * @author Juan Ricardo
 */
public class VentanaOcupado extends javax.swing.JFrame {
    
    private Plaza plaza;
    //Ventanas
    private VentanaPlazas ventanaPlazas; //Está será la ventana anterior que llama a esta.
    private AvisoDesasignar avisoDesasignar;

    /**
     * Creates new form VentanaOcupado
     */
    public VentanaOcupado(VentanaPlazas ventanaPlazas) {
        this.plaza=null;
        this.ventanaPlazas=ventanaPlazas;
        this.avisoDesasignar=null;
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JLabel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/7.jpg"))); // NOI18N

        jFormattedTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField6.setText((this.plaza==null)? "null" : this.plaza.getOcupante().getVehiculo().getPlaca());
        jFormattedTextField6.setEnabled(false);
        jFormattedTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField6ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel12.setText("PLACA: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow_left_opt.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 10, 110, 40));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText((this.plaza==null)? "-1" : Integer.toString(plaza.getNumero()));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 50, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel5.setText("FECHA INGRESO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 130, -1));

        jButton5.setBackground(new java.awt.Color(153, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("OCUPADO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 280, 40));

        jTextArea1.setColumns(1);
        jTextArea1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(1);
        jTextArea1.setText("Descripción del vehiculo");
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 360, 80));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel3.setText("DESCRIPCIÓN:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField2.setText((this.plaza==null)? "null" : this.plaza.getOcupante().getFechaEntrada());
        jFormattedTextField2.setEnabled(false);
        jFormattedTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 250, 30));

        jToggleButton1.setBackground(new java.awt.Color(255, 153, 0));
        jToggleButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log_off_opt.png"))); // NOI18N
        jToggleButton1.setText("DESOCUPAR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 180, 40));

        jSeparator1.setBackground(new java.awt.Color(255, 204, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 204, 51));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 520, 20));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel6.setText("ESTADO: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jToggleButton2.setBackground(new java.awt.Color(255, 204, 51));
        jToggleButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/printer_opt.png"))); // NOI18N
        jToggleButton2.setText("IMPRIMIR TICKET");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 190, 40));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setText("PLAZA N°");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel9.setText("MARCA:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jFormattedTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField4.setText((this.plaza==null)? "null" : this.plaza.getOcupante().getVehiculo().getPlaca());
        jFormattedTextField4.setEnabled(false);
        jFormattedTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 250, 30));

        jFormattedTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField5.setText((this.plaza==null)? "null" : this.plaza.getOcupante().getVehiculo().getMarca());
        jFormattedTextField5.setEnabled(false);
        jFormattedTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 250, 30));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel4.setText("COLOR:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel11.setText("TIPO: ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel13.setText("PLACA: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jFormattedTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField8.setText((this.plaza==null)? "null" : this.plaza.getOcupante().getVehiculo().getColor());
        jFormattedTextField8.setEnabled(false);
        jFormattedTextField8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 250, 30));

        jFormattedTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField7.setText((this.plaza==null)? "null" : this.plaza.getOcupante().getVehiculo().getPlaca());
        jFormattedTextField7.setEnabled(false);
        jFormattedTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 250, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gradient-highlight-linear-white-green-1920x1080-c2-66cdaa-ffffff-l-67-a-345-f-21.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ventanaPlazas.actualizarVentana();
        ventanaPlazas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
        this.jFormattedTextField2.setText(this.plaza.getOcupante().getFechaEntrada());
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        Date ahora = new Date();
        String fechaticket =  Integer.toString(ahora.getHours())+":"+Integer.toString(ahora.getMinutes())+":"+Integer.toString(ahora.getSeconds())+"  "+Integer.toString(ahora.getDate())+"/"+Integer.toString(ahora.getMonth()+1)+"/"+Integer.toString(ahora.getYear()+1900);
        String fecha = this.plaza.getOcupante().getFechaEntrada();
        String tipo = this.plaza.getOcupante().getVehiculo().getTipo();
        String plaza = Integer.toString(this.plaza.getNumero());
        String placa = this.plaza.getOcupante().getVehiculo().getPlaca();
        String marca = this.plaza.getOcupante().getVehiculo().getMarca();
        String color =this.plaza.getOcupante().getVehiculo().getColor();
        String desc = this.plaza.getOcupante().getVehiculo().getDescripcion();
        String Ticket = "                 SERVICIO DE PARQUEADERO             \n"+
        "\n"+  
        "=============================================================\n"+
        "                       BIENVENIDO(A)\n"+
        "=============================================================\n"+
        "\n"+  
        "      FECHA DE GENERACIÓN DEL TICKET:  "+fechaticket+"\n"+
        "      FECHA DE INGRESO:  "+fecha+"\n"+
        "      NÚMERO DE PLAZA:  "+plaza+"\n"+
        "\n"+  
        "=============================================================\n"+
        "                    DATOS DEL VEHICULO:\n"+
        "\n"+
        "       TIPO:        "+tipo+"\n"+
        "       PLACA:       "+placa+"\n"+
        "       MARCA:       "+marca+"\n"+
        "       COLOR:       "+color+"\n"+
        "       DESCRIPCIÓN: "+desc+"\n"+
        "\n"+  
        "=============================================================\n"+
        "                    INFORMACIÓN DEL PARQUEADERO:\n"+
        "\n"+
        "       VALOR FRACCIÓN(MINUTO): \n"+
        "       CARRO = $110 \n"+
        "       MOTO = $77\n"+
        "\n"+  
        "===============================================================\n"+            
        "\n"+  
        "CONSERVE ESTE TICKET HASTA QUE SU VEHICULO SALGA DEL PARQUEADERO\n"+
        "\n"+       
        "\n";
    try {
            FileWriter fw = new FileWriter("Ticket"+plaza+"-"+placa+".txt", true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            pw.print(Ticket);
            pw.close();
        } catch (IOException ex) {
            Logger.getLogger(VentanaOcupado.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Generando ticket...");
        try {
            Desktop.getDesktop().open(new File("Ticket"+plaza+"-"+placa+".txt"));
        } catch (IOException ex) {
            Logger.getLogger(VentanaOcupado.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed
    public double tiempoGenerado() {
        Date fecha = new Date();
        String fechaSalida = Integer.toString(fecha.getHours()) + ":" + Integer.toString(fecha.getMinutes()) + ":" + Integer.toString(fecha.getSeconds()) + "  " + Integer.toString(fecha.getDate()) + "/" + Integer.toString(fecha.getMonth() + 1) + "/" + Integer.toString(fecha.getYear() + 1900);
        double minutosEntrada = convertirFechaAMinutos(this.plaza.getOcupante().getFechaEntrada());
        double minutosSalida = convertirFechaAMinutos(fechaSalida);
        double tiempoTotal = (minutosSalida - minutosEntrada);
        return tiempoTotal;
        
    }
    private double convertirFechaAMinutos(String fecha) { //Halla los minutos contenidos en una fecha
        double valores[] = new double[6];
        int a;
        for (int i = 0; i < 2; i++) {
            a = fecha.indexOf(":");
            valores[i] = Double.parseDouble(fecha.substring(0, a));
            fecha = fecha.substring(a + 1);
        }
        a = fecha.indexOf(" ");
        valores[2] = Double.parseDouble(fecha.substring(0, a));
        fecha = fecha.substring(a + 1);
        for (int i = 3; i < 5; i++) {
            a = fecha.indexOf("/");
            valores[i] = Double.parseDouble(fecha.substring(0, a));
            fecha = fecha.substring(a + 1);
        }
        valores[5] = Double.parseDouble(fecha);
        return (valores[0] * 60) + valores[1] + (valores[3] * 1440) + (valores[4] * 43200) + (valores[5] * 518400);
    }

    /**
     * Genera el precio a pagar sigerido (Si se demora mas de un minuto en la
     * transacción cobra el minuto adicional pero no lo informa)
     *
     * @param fecha en formato String.
     */
    public double precioGenerado() {
        
        double precio = 0;

        if (this.plaza.getOcupante().getVehiculo().getTipo().equals("CARRO")) { //Se establece el tipo de vehiculo que se encontraba en él para establecer el valor a cobrar

            precio = Ticket.getValorPorMinutoCarros();
        } else {
            precio = Ticket.getValorPorMinutoMotos();
        }
        double time = this.tiempoGenerado();
        double precioT= Math.round(time*precio);
        return precioT;
        
    }
    private void jFormattedTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField4ActionPerformed
        // TODO add your handling code here:
        this.jFormattedTextField4.setText(this.plaza.getOcupante().getVehiculo().getMarca());
    }//GEN-LAST:event_jFormattedTextField4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        this.avisoDesasignar=new AvisoDesasignar(this.plaza, this.ventanaPlazas, this);
        this.avisoDesasignar.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jFormattedTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField5ActionPerformed

    private void jFormattedTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField6ActionPerformed

    private void jFormattedTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField7ActionPerformed

    private void jFormattedTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField8ActionPerformed

    public void actualizarVentana(Plaza plaza){
        this.plaza=plaza;
        this.jLabel1.setText(Integer.toString(this.plaza.getNumero()));
        this.jFormattedTextField4.setText((this.plaza==null)? "null" : this.plaza.getOcupante().getVehiculo().getTipo());
        this.jFormattedTextField7.setText((this.plaza==null)? "null" : this.plaza.getOcupante().getVehiculo().getPlaca());
        this.jFormattedTextField5.setText((this.plaza==null)? "null" : this.plaza.getOcupante().getVehiculo().getMarca());
        this.jFormattedTextField8.setText((this.plaza==null)? "null" : this.plaza.getOcupante().getVehiculo().getColor());
        //this.jFormattedTextField6.setText((this.plaza==null)? "null" : this.plaza.getOcupante().getVehiculo().getTipo());
        this.jTextArea1.setText((this.plaza==null)? "null" : this.plaza.getOcupante().getVehiculo().getDescripcion());
        this.jFormattedTextField2.setText((this.plaza==null)? "null" : this.plaza.getOcupante().getFechaEntrada());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
