package ventanas;

import clases.Conectar;
import clases.Admin;
import clases.FabricaAdmins;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author Juan Ricardo y Angel
 */

public class VentanaLogin extends javax.swing.JFrame {
    
    private InterfazPrincipal interfazPrincipal;
    private AvisoUsuarioError avisoUsuarioError;
    private FabricaAdmins fabAdm;
    
    public VentanaLogin() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.fabAdm = new FabricaAdmins();
        this.avisoUsuarioError = new AvisoUsuarioError();
        this.avisoUsuarioError.setLocationRelativeTo(null);
        
        
        //En esto me voy a basar para conectar la ventana login con la principal
        //this.interfazMovil = new InterfazMovil(this);
        //this.interfazMovil.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();
        cajaUsuario = new javax.swing.JFormattedTextField();
        jToggleButtonIngresar = new javax.swing.JToggleButton();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(153, 0, 0));
        Salir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 110, 40));

        titulo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("debidamente registrado. En caso de algún problema comuniquese con el administrador.");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 204, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 204, 51));
        jSeparator1.setFocusable(true);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 82, 960, 20));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INGRESE SUS DATOS DE USUARIO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 370, 20));

        titulo1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setText("SISTEMA DE PARQUEO DE AUTOMÓVILES");
        getContentPane().add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        titulo2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        titulo2.setForeground(new java.awt.Color(255, 255, 255));
        titulo2.setText("Bienvenido al Sistema de Gestion de Parqueaderos, el acceso solo es permitido a personal");
        getContentPane().add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardiaLogin(2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        titulo3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        titulo3.setForeground(new java.awt.Color(255, 255, 255));
        titulo3.setText("debidamente registrado. En caso de algún problema comuniquese con el administrador.");
        getContentPane().add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        cajaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(cajaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 260, 30));

        jToggleButtonIngresar.setBackground(new java.awt.Color(0, 255, 0));
        jToggleButtonIngresar.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jToggleButtonIngresar.setText("INGRESAR");
        jToggleButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, 210, 40));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 260, 30));

        jLabelContraseña.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setText("Contraseña:");
        getContentPane().add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 120, 20));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Usuario:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 90, 20));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoLogin.jpg"))); // NOI18N
        Fondo.setOpaque(true);
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1200, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_SalirActionPerformed

    private void cajaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaUsuarioActionPerformed

    private void jToggleButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonIngresarActionPerformed
        
        Conectar conexion = new Conectar();
        Connection reg = conexion.getConnection();
        
        String usuario = this.cajaUsuario.getText();
        String contraseña = String.valueOf(this.jPasswordField.getPassword());
        String pass=DigestUtils.md5Hex(contraseña); 
        String sql = "SELECT * FROM administrador WHERE usuario='"+usuario+"' AND contrasena='"+pass+"'";
        //String tipo = this.jComboBox1.getSelectedItem().toString();
        
        String datos [] = new String[8];
        Statement st;
        try {
            st = reg.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaRegistros.class.getName()).log(Level.SEVERE, null, ex);
        }
        conexion.desconectar();

        if(usuario.equals(datos[1]) && pass.equals(datos[2])){
            //Si se acepta el usuario, elimino los valores ingresados de las cajas de texto 
            this.cajaUsuario.setText("");
            this.jPasswordField.setText("");
            
            Admin admin = new Admin( Integer.parseInt(datos[0]), datos[1], datos[3], datos[4], datos[5], datos[6], datos[7]);
            //Creo la nueva interfaz principal dependiendo del usuario que ingresó.
            this.interfazPrincipal = new InterfazPrincipal(admin, this);
            this.interfazPrincipal.actualizarInterfaz();
            this.interfazPrincipal.setVisible(true);
            
            this.setVisible(false);
            
        }else{
            this.jPasswordField.setText("");
            this.avisoUsuarioError.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButtonIngresarActionPerformed

    public void setInterfazPrincipal(InterfazPrincipal interfazPrincipal){
        this.interfazPrincipal=interfazPrincipal;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Desplegar ventanas
                VentanaLogin frame = new VentanaLogin();
                frame.show(true);
                //frame.setLocationByPlatform(true);
                
                //Numero de coches que han usado el parqueadero, para el ID del ticket
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Salir;
    private javax.swing.JFormattedTextField cajaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButtonIngresar;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    // End of variables declaration//GEN-END:variables
}
