/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Parqueadero;
import java.awt.Desktop;
import java.io.File;

import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;





import clases.Conectar;

/**
 *
 * @author Juan Ricardo Y Angel Gomez
 */
public class VentanaRegistros extends VentanaPlazas {
    private final String ruta = System.getProperties().getProperty("user.dir");
    /**
     * Creates new form VentanaRegistros
     */
    public VentanaRegistros(Parqueadero parqueadero, InterfazPrincipal interfaz) {
       
        super(parqueadero,interfaz);
        initComponents();
        this.mostrarTabla(); 
    }

    void mostrarTabla(){
        Conectar conexion = new Conectar();
        Connection reg = conexion.getConnection();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("id_ocup");
            modelo.addColumn("placa_ocup");
            modelo.addColumn("num_plaza_ocup");
            modelo.addColumn("color_ocup");
            modelo.addColumn("marca_ocup");
            modelo.addColumn("descrip_ocup");
            modelo.addColumn("fecha_ingreso");
            modelo.addColumn("fecha_salida");
            tablaRegistros.setModel(modelo);
            
            String sql = "SELECT * FROM ocupante";
            String datos [] = new String[9];
            Statement st;
        try {
            st = reg.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                modelo.addRow(datos);
            }
            tablaRegistros.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaRegistros.class.getName()).log(Level.SEVERE, null, ex);
        }
        conexion.desconectar();
            
    }
    void buscarRegistro(){
                    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistros = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        cajaBuscar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buscarPor = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaBuscar = new javax.swing.JTable();
        docExcel = new javax.swing.JButton();
        docExcelBusq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HISTÓRICO DE REGISTROS DEL PARQUEADERO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 740, 40));

        tablaRegistros.setBackground(new java.awt.Color(255, 255, 204));
        tablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaRegistros.setGridColor(new java.awt.Color(0, 153, 51));
        jScrollPane1.setViewportView(tablaRegistros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 940, 170));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow_left_opt.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, -1));

        cajaBuscar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cajaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(cajaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 210, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search_opt.png"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 100, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Buscar por:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 120, 20));

        buscarPor.setBackground(new java.awt.Color(153, 255, 102));
        buscarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLACA", "PLAZA" }));
        buscarPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorActionPerformed(evt);
            }
        });
        getContentPane().add(buscarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 130, 30));

        tablaBuscar.setBackground(new java.awt.Color(255, 255, 204));
        tablaBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaBuscar.setGridColor(new java.awt.Color(255, 51, 51));
        jScrollPane3.setViewportView(tablaBuscar);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 940, 70));

        docExcel.setForeground(new java.awt.Color(0, 153, 0));
        docExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excel_opt.png"))); // NOI18N
        docExcel.setText("Crear documento excel");
        docExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docExcelActionPerformed(evt);
            }
        });
        getContentPane().add(docExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 190, 20));

        docExcelBusq.setForeground(new java.awt.Color(0, 153, 0));
        docExcelBusq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excel_opt.png"))); // NOI18N
        docExcelBusq.setText("Crear documento excel");
        docExcelBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docExcelBusqActionPerformed(evt);
            }
        });
        getContentPane().add(docExcelBusq, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 190, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shutterstock_154641665.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -140, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
       interfaz.actualizarInterfaz();
       interfaz.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cajaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaBuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Conectar conexion = new Conectar();
        Connection reg = conexion.getConnection();
        
        String busPor =  String.valueOf(buscarPor.getSelectedItem());
        String buscar = cajaBuscar.getText();
        DefaultTableModel modelo2 = new DefaultTableModel();
        modelo2.addColumn("id_ocup");
        modelo2.addColumn("placa_ocup");
        modelo2.addColumn("num_plaza_ocup");
        modelo2.addColumn("color_ocup");
        modelo2.addColumn("marca_ocup");
        modelo2.addColumn("descrip_ocup");
        modelo2.addColumn("fecha_ingreso");
        modelo2.addColumn("fecha_salida");
        tablaBuscar.setModel(modelo2);
        String sql = "";
        if(busPor == "PLACA"){
            sql = "SELECT * FROM ocupante WHERE placa_ocup='"+buscar+"'";
            }
        else if(busPor == "PLAZA"){
            sql = "SELECT * FROM ocupante WHERE num_plaza_ocup='"+buscar+"'";
        }
        //else if(busPor=="FECHA DE INGRESO"){
          //  sql = "SELECT * FROM ocupante WHERE fecha_ingreso='"+buscar+"'";
        //}
        String datos [] = new String[9];
        Statement st;
        try {
            st = reg.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                modelo2.addRow(datos);
            }
            tablaBuscar.setModel(modelo2);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaRegistros.class.getName()).log(Level.SEVERE, null, ex);
        }
        conexion.desconectar();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void buscarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarPorActionPerformed

    private void docExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docExcelActionPerformed
        if(tablaRegistros.getColumnCount()!=0){
        try{
        String file  = "dataParkingUIS..xls";
        TableModel model = tablaRegistros.getModel();
        FileWriter excel = new FileWriter(file);

        for(int i = 0; i < model.getColumnCount(); i++){
            excel.write(model.getColumnName(i) + "\t");
        }

        excel.write("\n");

        for(int i=0; i< model.getRowCount(); i++) {
            for(int j=0; j < model.getColumnCount(); j++) {
                excel.write(model.getValueAt(i,j).toString()+"\t");
            }
            excel.write("\n");
        }

        excel.close();
        JOptionPane.showMessageDialog(null, "Archivo excel creado con éxito");
        Desktop.getDesktop().open(new File("dataParkingUIS..xls"));
        }catch(IOException e){ System.out.println(e); }
        }
        else {
            JOptionPane.showMessageDialog(null, "No hay datos en la tabla para crear un archivo excel");
        }
    }//GEN-LAST:event_docExcelActionPerformed

    private void docExcelBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docExcelBusqActionPerformed
        if(tablaBuscar.getColumnCount()!=0){
            
        
        try{
        String file  = "BusquedaParkingUIS..xls";
        TableModel model = tablaBuscar.getModel();
        FileWriter excel = new FileWriter(file);

        for(int i = 0; i < model.getColumnCount(); i++){
            excel.write(model.getColumnName(i) + "\t");
        }

        excel.write("\n");

        for(int i=0; i< model.getRowCount(); i++) {
            for(int j=0; j < model.getColumnCount(); j++) {
                excel.write(model.getValueAt(i,j).toString()+"\t");
            }
            excel.write("\n");
        }

        excel.close();
        JOptionPane.showMessageDialog(null, "Archivo excel creado con éxito");
        Desktop.getDesktop().open(new File("BusquedaParkingUIS..xls"));
        }catch(IOException e){ System.out.println(e); }
        }
        else {
            JOptionPane.showMessageDialog(null, "No hay datos en la tabla para crear un archivo excel");
        }
        
    }//GEN-LAST:event_docExcelBusqActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> buscarPor;
    private javax.swing.JTextField cajaBuscar;
    private javax.swing.JButton docExcel;
    private javax.swing.JButton docExcelBusq;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaBuscar;
    private javax.swing.JTable tablaRegistros;
    // End of variables declaration//GEN-END:variables
}
