package ventanas;
import clases.Plaza;

/**
 *
 * @author Juan Ricardo
 */    
public class VentanaDisponible extends javax.swing.JFrame {
    
    private Plaza plaza;
    //Ventanas
    private VentanaPlazas ventanaPlazas; //Está será la ventana anterior que llama a esta.
    private AvisoAsignar avisoAsignar;
    private AvisoAsignarVacio avisoAsignarVacio;
    
    /**
     * Creates new form VentanaDisponible
     */
    
    public VentanaDisponible(VentanaPlazas ventanaPlazas) {
        
        this.ventanaPlazas=ventanaPlazas;
        this.avisoAsignar=null;
        this.avisoAsignarVacio=new AvisoAsignarVacio();
        this.plaza=null;
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cajaPlaca = new javax.swing.JFormattedTextField();
        cajaColor = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cajaMarca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cajaDesc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow_left_opt.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 10, 110, 40));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText((this.plaza==null)? "-1" : Integer.toString(this.plaza.getNumero()));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 80, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel2.setText("COLOR:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jButton5.setBackground(new java.awt.Color(1, 186, 63));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText(" DISPONIBLE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 280, 40));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel3.setText("DESCRIPCION:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        cajaPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(cajaPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 280, 30));

        cajaColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaColorActionPerformed(evt);
            }
        });
        cajaColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaColorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaColorKeyTyped(evt);
            }
        });
        getContentPane().add(cajaColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 280, 30));

        jToggleButton1.setBackground(new java.awt.Color(255, 153, 0));
        jToggleButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/car_add_opt (1).png"))); // NOI18N
        jToggleButton1.setText("ASIGNAR CUPO");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 210, 40));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel5.setText("ESTADO: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 204, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 204, 51));
        jSeparator1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 520, 20));

        cajaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(cajaMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 280, 30));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setText("PLAZA N° ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        cajaDesc.setToolTipText("");
        cajaDesc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cajaDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaDescActionPerformed(evt);
            }
        });
        getContentPane().add(cajaDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 280, 30));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel8.setText("MARCA:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel9.setText("TIPO: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel10.setText("PLACA: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARRO", "MOTO"}));
        jComboBoxTipo.setSelectedIndex(0);
        getContentPane().add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 180, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gradient-highlight-linear-white-green-1920x1080-c2-66cdaa-ffffff-l-67-a-345-f-21.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       ventanaPlazas.actualizarVentana();
       ventanaPlazas.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cajaPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaPlacaActionPerformed
              
    }//GEN-LAST:event_cajaPlacaActionPerformed

    private void cajaColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaColorActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String placa = cajaPlaca.getText(); 
        String tipo = String.valueOf(jComboBoxTipo.getSelectedItem());
        String color = cajaColor.getText(); 
        String marca = cajaMarca.getText();
        String descripcion = cajaDesc.getText();
        //String tipo = this.jComboBox1.getSelectedItem().toString();
        
        if(placa.equals("") || color.equals("") || marca.equals("")){
            this.avisoAsignarVacio.setVisible(true);
       
        }else{
            this.avisoAsignar=new AvisoAsignar(this.plaza,this.ventanaPlazas,this,placa,marca,color,descripcion,tipo);
            this.avisoAsignar.setVisible(true);
        
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void cajaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaMarcaActionPerformed

    private void cajaDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaDescActionPerformed

    private void cajaColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaColorKeyTyped
       //char c = evt.getKeyChar();
       //if (c<'A' || c>'Z')evt.consume();
    }//GEN-LAST:event_cajaColorKeyTyped

    private void cajaColorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaColorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaColorKeyReleased

    //Como quiero usar esta ventana de forma general, le iré cambiando la plaza dinámicamente al mismo objeto
    public void actualizarVentana(Plaza plaza){
        this.plaza=plaza;
        this.jLabel1.setText(Integer.toString(this.plaza.getNumero()));
        this.cajaPlaca.setText("");
        this.cajaMarca.setText("");
        this.cajaColor.setText("");
        this.cajaDesc.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cajaColor;
    private javax.swing.JTextField cajaDesc;
    private javax.swing.JTextField cajaMarca;
    private javax.swing.JFormattedTextField cajaPlaca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
